Gabut Packages
frizkyiman/friWrt-MyWrtBuilder pull request #13
Opened 2024-03-14 19:16 UTC by rtaserver

Gabut Tambahin Packages. Suka ada yg butuh. Seperti Saya :v

- NetMon lumayan lah buat Test Speed LB :v 
- Base64 Lumayan Buat Convert Vmess
- Mikhmon ya buat Manage mikrotik

![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/79240886-6d90-4084-9814-e3db5e4535e0)
![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/75d4cfd6-71eb-4096-91fb-71997f973c2e)
![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/02438057-8935-4d6d-a2b8-a8ef01665053)
![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/f87f7527-a9dd-4082-bebf-03cec3096740)

2024-03-15 13:44 UTC, rtaserver commented
Test Add Tunnel Neko

2024-03-15 19:44 UTC, rtaserver commented
Final Build Add Paswall2 + Neko

![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/8173474a-236d-4236-b452-c87dedf3e514)
![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/bc1c74e7-dae4-4fbf-8ea6-99987df13f07)

Tested ViBox x86-64
![image](https://github.com/frizkyiman/friWrt-MyWrtBuilder/assets/142883865/2452c6b3-23d8-49ae-ae1a-c6d550520d21)

2024-03-22 10:57 UTC, frizkyiman requested changes
[201fd3f8a9e6a52ef40c96646bce636c1dc5b82c ](https://github.com/frizkyiman/friWrt-MyWrtBuilder/pull/13/commits/201fd3f8a9e6a52ef40c96646bce636c1dc5b82c)gk perlu tambah mikhmon, karna gk semua user pake, jd base64 sama netmon aja yg di tambah.

2024-03-22 11:44 UTC, frizkyiman approved these changes

2024-03-22 14:52 UTC, merged